version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 99
  assignees:
  - fyvfyv
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.26.2
    - 5.27.1
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: eslint
    versions:
    - 7.22.0
